Repository HAECHI-LABS/vvisp, pull requests merged in 2018-11, with the labels that each got.

#9 npm install --global haechi-cli is not working.
  README.md
Labels: Docs

#10 docs: add english version of CONTRIBUTING.md and update CONTRIBUTING
  CONTRIBUTING-ko.md
  CONTRIBUTING.md
Labels: Docs

#14 fix: fix bugs of init caused by lerna
  packages/haechi-cli/referenceFiles/.solcover.js
  packages/haechi-cli/referenceFiles/.soliumignore
  packages/haechi-cli/referenceFiles/.soliumrc.json
  packages/haechi-cli/scripts/init.js
Labels: bug, feature: init

#16 fix: fix bug #13
  packages/vvisp/contracts/test/DependencyB.sol
  packages/vvisp/contracts/test/DependencyD.sol
  packages/vvisp/scripts/deploy-service/processes/injectVar.js
  packages/vvisp/test/dummy/justNonUpgradeables.service1.json
  packages/vvisp/test/dummy/justNonUpgradeables.service2.json
  packages/vvisp/test/dummy/service1.json
  packages/vvisp/test/dummy/service2.json
Labels: bug, feature: deploy-service

#17 docs: refine documentations, CONTRIBUTING and README
  CONTRIBUTING-ko.md
  CONTRIBUTING.md
  README.md
Labels: Docs
